package model;
// Generated 05/12/2019 09:47:29 AM by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idAlum;
     private String nomAlum;
     private Integer nota;

    public Alumno() {
    }

    public Alumno(String nomAlum, Integer nota) {
       this.nomAlum = nomAlum;
       this.nota = nota;
    }
   
    public Integer getIdAlum() {
        return this.idAlum;
    }
    
    public void setIdAlum(Integer idAlum) {
        this.idAlum = idAlum;
    }
    public String getNomAlum() {
        return this.nomAlum;
    }
    
    public void setNomAlum(String nomAlum) {
        this.nomAlum = nomAlum;
    }
    public Integer getNota() {
        return this.nota;
    }
    
    public void setNota(Integer nota) {
        this.nota = nota;
    }




}


